---
title: "Meldeeimer"
author: "H端rth"
lang: de
format: 
  dashboard:
    logo: inputs/meldeeimer_logo.svg
    orientation: columns
    theme: litera
    embed-resources: true
---

```{r}
#| include: false
# set local and timezone
Sys.setlocale("LC_TIME", "German.UTF-8")
Sys.setenv(TZ = "Europe/Berlin")

# save time of run to document
time_current <- Sys.time()
time_24h_ago <- time_current - 24*60*60

# import functions
source("meldee_get_bin_metadata.R")
source("meldee_get_bins.R")
source("meldee_get_reports.R")
source("meldee_filter_valid_reports.R")
source("meldee_update_report_uuid.R")
```

```{r}
# get bin metadata
geojson <- "https://raw.githubusercontent.com/gkalvelage/huerth/main/inputs/bins_encrypted.geojson"
bin_metadata <- meldee_get_bin_metadata(geojson)

# create data frame of bins
bins <- meldee_get_bins(bin_metadata)

# get reports
reports <- meldee_get_reports()

# keep only reports with valid UUID
reports <- meldee_filter_valid_reports(reports, bin_metadata)

# replace historical UUID with current UUID, i.e. combine reports for bin
reports <- meldee_update_report_uuid(reports, bin_metadata)
```

```{r}
# merge bin metadata to individual reports
reports <- merge(reports, bins, by = "uuid")

# aggregate reports for every bin
reports$count <- 1
reports_sum <- aggregate(count ~ uuid + bin_id + lon + lat, data = reports, FUN = length)
```

```{r}
library("lubridate")

last7days <- reports |>
  dplyr::filter(datetime >= time_current - lubridate::days(7))

last7days_sum <- aggregate(count ~ uuid + bin_id + lon + lat, data = last7days, FUN = length)

last6months <- reports |>
  dplyr::filter(datetime >= time_current %m-% months(6))

last6months_sum <- aggregate(count ~ uuid + bin_id + lon + lat, data = last6months, FUN = length)
```


# Letzte 7 Tage {width=25%}

## KPI

```{r}
#| component: valuebox
#| title: "Meldungen"
list(
  icon = "flag",
  color = "danger",
  value = as.numeric(nrow(last7days))
)
```

```{r}
#| component: valuebox
#| title: "M端lleimer"
list(
  icon = "trash",
  color = "warning",
  value = as.numeric(nrow(last7days_sum))
)
```

```{r}
#| component: valuebox
#| title: "Meldungen < 24h"
list(
  icon = "clock-history",
  color = "secondary",
  value = as.numeric(nrow(reports[reports$datetime >= time_24h_ago, ]))
)
```

## Heatmap {width=75%}

```{r}
cat("title=", "Meldungen: letzte 7 Tage")

# create a color palette for the values
pal <- leaflet::colorNumeric(palette = "plasma", domain = last7days_sum$count)

# compute the convex hull to identify outer most points
hull_indices <- chull(bins$lon, bins$lat)
hull_indices <- c(hull_indices, hull_indices[1])  # close polygon
border <- bins[hull_indices, ] # extract the border coordinates

# create heatmap of overall reports
leaflet::leaflet(last7days_sum) |>
  leaflet::addTiles() |>
  # leaflet::addPolygons(lng = border$lon,
  #                      lat = border$lat,
  #                      fillOpacity = 0.1) |>
  # bounds <- sf::read_sf("inputs/huerth_admin_boundaries.geojson")
  # leaflet::addPolygons(data = bounds, fillOpacity = .1) |>
  leaflet::addCircleMarkers(
    lng = ~ lon,
    lat = ~ lat,
    radius = ~ sqrt(count) * 5,
    label = ~ paste0(bin_id, ": ", count, ifelse(count == 1, " Meldung", " Meldungen")),
    color = ~ pal(count),
#    clusterOptions = leaflet::markerClusterOptions(),
    stroke = FALSE,
    fillOpacity = .75
  ) |>
  leaflet::addLegend(
    "bottomright",
    pal = pal,
    values = ~ count,
    title = "Meld-<br>ungen",
    opacity = 1  )
```

::: {expandable="false" style="font-size: 65%; text-align: right;"}
Zuletzt aktualisiert: `r format(time_current, "%d.%m.%Y, %H:%M")` Uhr.<br>[Hintergrund](https://meldeeimer.de/huerth) - [Impressum](https://meldeeimer.de/impressum) - [Datenschutz](https://meldeeimer.de/datenschutz)
:::

# Letzte 6 Monate {width=25%}

## KPI

```{r}
#| component: valuebox
#| title: "Meldungen"
list(
  icon = "flag",
  color = "danger",
  value = as.numeric(nrow(last6months))
)
```

```{r}
#| component: valuebox
#| title: "M端lleimer"
list(
  icon = "trash",
  color = "warning",
  value = as.numeric(nrow(last6months_sum))
)
```

```{r}
#| component: valuebox
#| title: "Meldungen < 24h"
list(
  icon = "clock-history",
  color = "secondary",
  value = as.numeric(nrow(reports[reports$datetime >= time_24h_ago, ]))
)
```

## Heatmap {width=75%}

```{r}
cat("title=", "Meldungen: letzte 6 Monate")

# create a color palette for the values
pal <- leaflet::colorNumeric(palette = "plasma", domain = last6months_sum$count)

# compute the convex hull to identify outer most points
hull_indices <- chull(bins$lon, bins$lat)
hull_indices <- c(hull_indices, hull_indices[1])  # close polygon
border <- bins[hull_indices, ] # extract the border coordinates

# create heatmap of overall reports
leaflet::leaflet(last6months_sum) |>
  leaflet::addTiles() |>
  # leaflet::addPolygons(lng = border$lon,
  #                      lat = border$lat,
  #                      fillOpacity = 0.1) |>
  # bounds <- sf::read_sf("inputs/huerth_admin_boundaries.geojson")
  # leaflet::addPolygons(data = bounds, fillOpacity = .1) |>
  leaflet::addCircleMarkers(
    lng = ~ lon,
    lat = ~ lat,
    radius = ~ sqrt(count) * 5,
    label = ~ paste0(bin_id, ": ", count, ifelse(count == 1, " Meldung", " Meldungen")),
    color = ~ pal(count),
#    clusterOptions = leaflet::markerClusterOptions(),
    stroke = FALSE,
    fillOpacity = .75
  ) |>
  leaflet::addLegend(
    "bottomright",
    pal = pal,
    values = ~ count,
    title = "Meld-<br>ungen",
    opacity = 1  )
```

::: {expandable="false" style="font-size: 65%; text-align: right;"}
Zuletzt aktualisiert: `r format(time_current, "%d.%m.%Y, %H:%M")` Uhr.<br>[Hintergrund](https://meldeeimer.de/huerth) - [Impressum](https://meldeeimer.de/impressum) - [Datenschutz](https://meldeeimer.de/datenschutz)
:::

# Datentabelle {orientation="rows"}

```{r}
# create link to OSM
reports$location <- paste0(
  '<a href="https://www.openstreetmap.org/?mlat=',
  reports$lat,
  '&mlon=',
  reports$lon,
  "#map=14/",
  reports$lat,
  "/",
  reports$lon,
  '" target="_blank">',
  paste(round(reports$lat, 5), round(reports$lon, 5), sep = ", "),
  '</a>'
)

# separate date and time for better readability
reports$date <- as.Date(reports$datetime)
reports$time <- format(reports$datetime, format = "%H:%M:%S")

# sort last report on top
reports <- reports[order(reports$datetime, decreasing = TRUE), ]

# print table
DT::datatable(
  reports[, c("date", "time", "bin_id", "response", "location")],
  escape = FALSE,
  colnames = c("Datum", "Uhrzeit", "M端lleimer-Nr.", "Meldegrund", "Standort"),
  rownames = FALSE,
  filter = "top",
  extensions = 'Buttons',
  callback = DT::JS('
    $(\'div.has-feedback input[type="search"]\').attr("placeholder", "(alle)");
    $(\'div.has-feedback input[type="search"]\').css({
      "font-size": "0.8em",
      "text-align": "right"
    });
  '),
  options = list(
    dom = "Bitp",
    buttons = c('csv', 'excel', 'pdf'),
    searchHighlight = TRUE,
    pageLength = 10,
    columnDefs = list(list(
      className = 'dt-right', targets = '_all'
    )),
    language = list(url = "//cdn.datatables.net/plug-ins/2.1.3/i18n/de-DE.json", info = "_TOTAL_ Meldungen")
  )
)
```

::: {expandable="false" style="font-size: 65%; text-align: right;"}
Zuletzt aktualisiert: `r format(time_current, "%d.%m.%Y, %H:%M")` Uhr.<br>[Hintergrund](https://meldeeimer.de/huerth) - [Impressum](https://meldeeimer.de/impressum) - [Datenschutz](https://meldeeimer.de/datenschutz)
:::
